.github/workflows/build-on-publish-release.yaml
.github/workflows/build-on-release.yaml
holmes.py
holmes/__init__.py

Up until now you had to remember to update the version manually

Set version automatically during release

---

.github/workflows/build-on-release.yaml

@Avi-Robusta note: we should do the same for KRR too.

Increase compatibility of linux binaries

---

holmes.py
holmes/utils/file_utils.py

`poetry run python3 holmes.py ask "What is the issue with payment-processing-worker" -raw-json-file="out.json"`

added option to dump complete raw data to json

---

README.md

Update README in accordance w/ #20 to show Docker command without a version placeholder. Also fix a typo.

Update README.md references to Docker image

---

.github/workflows/build-binaries-and-brew.yaml

Fixes https://github.com/robusta-dev/holmesgpt/actions/runs/9536634152

Fix windows build

---

README.md

Thank you @samgabrail for the feedback

Document environment variables for api key

---

README.md
holmes.py
holmes/core/tool_calling_llm.py

add --file flag

---

holmes/__init__.py

It gave unwanted output due to STDERR not being captured

Fix version command when it runs outside of a git repo

---

holmes/config.py

Remove unecessary code for config

---

helm/holmes/templates/holmes.yaml
helm/holmes/values.yaml
holmes/plugins/destinations/slack/plugin.py
server.py
test-api.sh

fix slack upload - change to new api

update holmes chart

---

holmes/main.py

Right now this PR only touches the jira command, but similar PRs will follow for other commands later.

Minor improvements to allow testing `investigate` commands more easily

---

README.md
pyproject.toml

I have been using pipx myself for recent installs and have had an excellent experience. It works very well.

Add pipx installation instructions

---

holmes/main.py

Add slack destination to ask command

---

helm/holmes/templates/holmesgpt-service-account.yaml

Added Prometheus Operator RBAC for holmes to service accout template 
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/rbac.md#prometheus-operator-rbac

Added Prometheus Operator RBAC for holmes to service accout template

---

config.example.yaml
holmes/main.py

Note to whoever reviews this: we are removing the default value for the model from *main.py* but we are **not** removing the default value. The default is still defined in *config.py* as it should be. The unecessary redefining of the default in main.py caused the bug.
Thank you to @vfarcic for reporting.

Allow reading model param from config file

---

holmes/core/issue.py
holmes/core/tool_calling_llm.py
holmes/plugins/sources/pagerduty/__init__.py

This change does not impact holmes' behaviour. It adds some comments to the code and makes upper/lowercase more consistent.
It includes most of the non-functional changes from the rds_flow_investigation that we are merging in pieces.

comments and casing

---

holmes/main.py

e.g. run `poetry run holmes ask "what is wrong with my cluster?" --no-echo` and the user's question will not be echoed back to them. This is useful for scripting scenarios.

allow not echoing user request

---

README.md

Updated the plugin to create a temporary file thats not left behind after using it.

Updated K9s plugin

---

Dockerfile
Dockerfile.dev

updated go package github.com/docker/docker in kube-lineage,
ran kube lineage with no issues

MAIN-2111 patching Holmes-CVE-2024-41110

---

holmes/core/tool_calling_llm.py
holmes/main.py
holmes/plugins/prompts/__init__.py
holmes/plugins/prompts/_general_instructions.jinja2
holmes/plugins/prompts/generic_ask.jinja2
holmes/plugins/prompts/generic_ask_for_issue_conversation.jinja2
holmes/plugins/prompts/generic_investigation.jinja2
server.py

Use jinja2 template includes so we don't repeat prompts everywhere.
Tests

Reuse prompts

---

holmes/core/supabase_dal.py

Useful when the token is pulled from a secret

allow overriding the UI token with an env var.

---

holmes/core/tool_calling_llm.py

--model="openai/gpt-4o" would throw an exception due to no longer including the prefix openai in the model_cost table
https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json

Bugfix - backwards compatibility with model names for openai

---

helm/holmes/templates/holmesgpt-service-account.yaml
holmes/plugins/toolsets/kubernetes.yaml

Added kubectl top action

---

holmes/core/supabase_dal.py
holmes/core/tool_calling_llm.py
holmes/core/tools.py

Fix bug in jwt retry - patch was not called
Fix bug if a non existing tool was called
Fix bug if tool arguments is not a valid json
Add MODEL_TYPE env var, to support azure token counting

bug fixes:

---

helm/holmes/values.yaml

increase default memory allocation to support browsing

use internet tool by default on the chart

---

holmes/plugins/prompts/_general_instructions.jinja2
holmes/plugins/toolsets/kubernetes.yaml
tests/fixtures/test_chat/3_what_is_the_command_to_port_forward/kubectl_describe.txt
tests/fixtures/test_chat/3_what_is_the_command_to_port_forward/test_case.yaml
tests/fixtures/test_chat/4_related_k8s_events/kubectl_events.txt
tests/fixtures/test_chat/7_get_pod_events/kubectl_events.txt
tests/fixtures/test_chat/7_get_pod_events/kubectl_find_resource.txt
tests/fixtures/test_chat/7_get_pod_events/test_case.yaml
tests/test_chat.py

- Update the prompt to ask the LLM to be specific. Also mention instructions to fetch the port of a pod to port forward
- Add a kubectl tool to fetch events
Tests have been updated accordingly

Add kubectl events capability & improve prompt

---

holmes/main.py

fix: issues due to console cleanup/refactor

---

holmes/utils/robusta.py

`if os.environ.get("ROBUSTA_AI"):` will be true even if env var ROBUSTA_AI is set to 'false'

bugfix ROBUSTA_AI env var

---

examples/custom_llm.py
holmes/plugins/toolsets/grafana/toolset_grafana_loki.py

(the example given in custom_llm.py right now doesn't work)

loki toolset improvements + unrelated fix to example python code

---

helm/holmes/templates/holmes.yaml
helm/holmes/values.yaml

verified via running helm chart locally

[ROB-792 ] added node selector

---

holmes/plugins/toolsets/prometheus.py
tests/test_prometheus_unit.py

- Authentication support through headers
- Alt API for:
- labels
- metadata (list all metrics)
- Option for tool calls to return data

feat: prometheus: alt. API for series labels, option to return data

---

holmes/core/tool_calling_llm.py
holmes/plugins/toolsets/robusta/robusta_instructions.jinja2

fixed merge issue

---

holmes/plugins/toolsets/aks-node-health.yaml

adding a new toolset to focus troubleshooting an AKS node health issue.

Creating a AKS node health toolset

---

holmes/core/investigation.py
holmes/core/tool_calling_llm.py

Fix a bug that swallows exception on bad completion request

If using Gemini - disable structured output

---

.github/workflows/build-binaries-and-brew.yaml

Update `build-binaries-and-brew.yaml` to match `build-and-test.yaml`

Possible fix for release process

---

docs/development/index.md
docs/index.md
docs/installation/cli-installation.md
docs/installation/kubernetes-installation.md
docs/installation/python-installation.md
docs/installation/ui-installation.md
docs/reference/troubleshooting.md
docs/walkthrough/index.md
mkdocs.yml

Thanks, @Sheeproid, for the feedback!

Fixes broken Slack link and page edit buttons

---

holmes/utils/cache.py

Replace bz2 with zlib. bz2 requires extra library `apt-get install libbz2-dev`

chore: use zlib to compress/decompress data

---

holmes/interactive.py

Fixes #721 and also combines q, escape and c-c

Fixed double exit crash in /show

---

docs/reference/helm-configuration.md
holmes/plugins/destinations/slack/plugin.py

Potential fix for Holmes failing with content type issue
```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/runner/.local/lib/python3.12/site-packages/holmes/main.py:336 in ask   │
│                                                                              │
│   333 │   │   raw={"prompt": prompt, "full_conversation": messages},         │
│   334 │   │   source_instance_id=socket.gethostname(),                       │
│   335 │   )                                                                  │
│ ❱ 336 │   handle_result(                                                     │
│   337 │   │   response,                                                      │
│   338 │   │   console,                                                       │
│   339 │ …
```

Slack file upload fix

---

holmes/plugins/toolsets/aks-node-health.yaml

Removing the tool to executive arbitrary commands in VMSS

Remove vmss run command

---

tests/llm/fixtures/test_ask_holmes/110_k8s_events_image_pull/deployment.yaml
tests/llm/fixtures/test_ask_holmes/110_k8s_events_image_pull/test_case.yaml

add eval for k8s events

---

docs/development/evals/index.md

it was accidentally removed during a recent rewrite of the docs I did

add docs on ASK_HOLMES_TEST_TYPE

---

holmes/plugins/toolsets/logging_utils/logging_api.py
tests/plugins/toolsets/test_logging_api.py

bugfix: convert int to str to support negative int values

---

CLAUDE.md
README.md
docs/cncf-self-assesment.md
docs/overrides/main.html
holmes/plugins/prompts/_permission_errors.jinja2
holmes/plugins/prompts/_toolsets_instructions.jinja2
holmes/plugins/toolsets/runbook/runbook_fetcher.py
mkdocs.yml
tests/llm/fixtures/test_ask_holmes/16_failed_no_toolset_found/test_case.yaml
tests/llm/fixtures/test_ask_holmes/28_permissions_error/test_case.yaml

Fixes a broken URL path and changes an old URL

Minor docs fix

---

tests/llm/fixtures/test_ask_holmes/111_disabled_datadog_traces/test_case.yaml
tests/llm/fixtures/test_ask_holmes/43_slack_deployment_logs/test_case.yaml
tests/llm/fixtures/test_ask_holmes/44_slack_statefulset_logs/test_case.yaml
tests/llm/fixtures/test_ask_holmes/57_cluster_name_confusion/test_case.yaml
tests/llm/fixtures/test_ask_holmes/92_cpu_graph_conversation/test_case.yaml
tests/llm/fixtures/test_ask_holmes/93_calling_datadog/test_case.yaml
tests/llm/test_ask_holmes.py
tests/llm/test_investigate.py
tests/llm/test_workload_health.py
tests/llm/utils/braintrust.py
tests/llm/utils/commands.py
tests/llm/utils/property_manager.py
tests/llm/utils/setup_cleanup.py
tests/llm/utils/test_case_utils.py

Fixes
* tests that failed during setup are now reported properly to braintrust
* minor fixes to datadog tests

evals: better error reporting and other fixes

---

conftest.py

Braintrust was blocked causing multiple timeouts and retries

Fix bug causing massive evals slowdown

---

poetry.lock
pyproject.toml

HTTP connection will always fail when using socks proxy. This PR fixes this issue by adding the missing dependency.

Fix the httpx dependency to make it compatible with http_proxy
