README.md
holmes.py
holmes/config.py
holmes/plugins/interfaces.py
holmes/plugins/sources/github/__init__.py

* Adds the GitHub integration as per issue #13
* Fixes minor typos here and there
* Allows us to run: `holmes investigate github --github-repository=holmesgpt --github-owner=robusta-dev --github-pat=your_personal_access_token --github-query="is:pr is:closed (whatever query you want)"`
* Quickly tested, might need some refactoring here and there, but everything is working.

Add the GitHub integration as per issue#13

---

holmes.py
holmes/plugins/sources/github/__init__.py

This is allowed in python 3.12 (see [here](https://realpython.com/python312-f-strings/#:~:text=In%20Python%203.12's%20f%2Dstrings,in%20brackets%20outside%20f%2Dstrings.)) but not earlier versions.

Fix unwanted linebreaks

---

holmes.py
holmes/config.py
holmes/plugins/sources/prometheus/plugin.py

Example run
```
kubectl apply -f https://raw.githubusercontent.com/robusta-dev/kubernetes-demos/main/pending_pods/pending_pod_node_selector.yaml
poetry run python3 /Users/avirobusta/git/holmesgpt/holmes.py investigate alertmanager --alertmanager-url=http://localhost:9093/ --alert-label-key=pod --alert-label-value=user-profile-import
Configuration file exists at /Users/avirobusta/Library/Preferences/pypoetry, reusing this directory.
Consider moving TOML configuration files to /Users/avirobusta/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Analyzing all 1 issues. (Use --alertmanager-alertname to filter.) Press Ctrl+C to stop.
Analyzing issue 1/1: KubePodNotReady...
No runbooks found for this issue. Using default behaviour. …
```

added filter on alert by label

---

holmes/plugins/prompts/generic_ask.jinja2

Without this change, the ask command occasionally gives "lazy output" like stating that a pod is pending but not investigating why.
I ran our benchmarks on this branch to verify that this change fixes the problem and does not cause regressions for other test scenarios. I tested our scenarios with --repeat=5. All tests passed according to the LLM evaluated-results. I then reviewed all the test output manually to verify that there were no undesired consequences of this change in LLM output.
The results look better to me as a result of this change, and I can confirm that is reduces LLM-laziness. (The LLM was not lazy in a single test scenario after this change.)

Improve prompt to fix failing tests

---

holmes/__init__.py

so it doesn't depend on the directory holmes was run from

Fix version command

---

Dockerfile
README.md
holmes/config.py
holmes/main.py
holmes/plugins/destinations/slack/plugin.py
holmes/utils/pydantic_utils.py

This makes holmes behave like other command line tools (e.g. kubectl) and more like users expect. This came up in a recent user feedback call.

Read default config file from ~/.holmes/config.yaml not current directory

---

holmes/plugins/sources/prometheus/plugin.py

Fixes
```
Traceback (most recent call last):                                                                         
alertmanager                                                                                               
issues = source.fetch_issues()                                                                         
^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                     
line 96, in fetch_issues                                                                                   
alertname_filter = re.compile(self.alertname)                                                          
^^^^^^^^^^^^^^ …
```

Fixing alert filter using alertname

---

README.md

The latest tag doesn't exist on the -dev version of the image. We should use the regular one.
Fixes #121

Fix wrong docker image in README.md

---

holmes/plugins/prompts/generic_investigation.jinja2

This change leads openAI gpt-4o to not return the Tools used directly in the text response.
This has been tested for the following models:
- gpt-4o
- gpt-3.5-turbo
- o1-mini 
- claude-3-opus-20240229
- claude-3-5-sonnet-20241022

Avoid listing tools used during investigations

---

holmes/config.py

This PR ensures builtin toolsets are loaded only at initialization time.
This makes sure that the prerequisite checks for each toolset is only run at startup and not for every API call to the server.
If we want this behaviour to also apply to the custom toolsets, then this PR is not enough.

Only load builtin toolsets when the config is initialised

---

helm/holmes/templates/holmes.yaml
helm/holmes/values.yaml

This PR adds support for Kubernetes pod affinity configurations in the Holmes Helm chart, enabling users to define custom pod scheduling rules through the values file.
- Added `affinity` configuration option in `values.yaml` with an empty default object
- Implemented affinity support in the deployment template using Helm's `toYaml` function
- Configured the template to conditionally include affinity settings when provided
Users can now define pod affinity rules in their values file:
```yaml
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: nodepool
operator: In
values:
- private
```
- [ X ] Verified Helm template renders correctly with empty affinity
- [ X ] Verified Helm template renders correctly with sample affinity …

Add Pod Affinity Configuration Support to Helm Chart

---

holmes/common/env_vars.py
holmes/config.py
holmes/core/investigation.py
holmes/core/llm.py
holmes/core/performance_timing.py
holmes/core/tool_calling_llm.py
holmes/utils/global_instructions.py
server.py
tests/llm/test_investigate.py

Mostly minor changes:
- Remove the use of `Console` from server.py. This cascades into other changes downstream
- Add latency logs behind a `LOG_PERFORMANCE` env var: 
- Add a wrapper for all API calls to measure the latency at API level
- Add detailed performance monitoring to the tool_calling_llm core `call()` function
- Align the http server (uvicorn) logging pattern with the other logging calls
Example of perf metrics for tool_calling_llm:
```
2025-01-14 09:41:17.177 INFO     tool_calling_llm.call(TOTAL) 8167ms
2025-01-14 09:41:17.177 INFO     	tool_calling_llm.call(get_all_tools_openai_format) +0ms  0ms
2025-01-14 09:41:17.177 INFO     	tool_calling_llm.call(start iteration 0) +0ms  0ms
2025-01-14 09:41:17.177 INFO     	tool_calling_llm.call(count tokens) +6ms  6ms
2025-01-14 …
```

feat: improve logging and add optional perf logging

---

holmes/core/investigation.py
holmes/core/investigation_structured_output.py
holmes/core/models.py
holmes/core/tool_calling_llm.py
server.py

The code to parse the sections for the custom RCA output was in the wrong place, causing it meddle with the structured output from the workload health checks.
This PR moves this code out of the tool_calling_llm.py into the investigation helper

fix: issue with sections handling messing workload health structured output

---

Dockerfile

Fix for this build issue: https://github.com/robusta-dev/holmesgpt/actions/runs/13054902903

fix: dockerfile should download appropriate image for arm64

---

holmes/core/tool_calling_llm.py

Fixes the issue below:
```bash
2025-02-26 12:05:05.053 ERROR    Error in /api/chat: Invalid tool choice, tool_choice=NOT_GIVEN. Got=<class 'openai.NotGiven'>. Expecting str, or dict. Please ensure tool_choice follows the OpenAI tool_choice spec
Traceback (most recent call last):
File "/app/server.py", line 275, in chat
llm_call = ai.messages_call(messages=messages)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/holmes/core/tool_calling_llm.py", line 105, in messages_call
return self.call(messages, post_process_prompt, response_format)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/holmes/core/tool_calling_llm.py", line 143, in call
full_response = self.llm.completion(
^^^^^^^^^^^^^^^^^^^^
File "/app/holmes/core/llm.py", line 172, in completion
result = …
```

fix: litellm throws NOT_GIVEN error for tool_choice when max_steps is reached

---

holmes/config.py
holmes/plugins/toolsets/opensearch.py

- Holmes would sometimes halucinate cluster names for multi configured opensearch clusters.
- The logic for get_client was broken for more than 1 cluster (would check var that wasnt there)
- misc other bug fixes

Multiple opensearch cluster suport

---

holmes/plugins/toolsets/kafka.py

allowed for multi kafka cluster support
example config
```  
kafka/admin:
config:
kafka_clusters:
- name: aks-prod-kafka
kafka_broker: aks-prod-kafka-1.aks-prod-kafka-brokers.kafka.svc:9095
kafka_username: kafka-plaintext-user
kafka_password: ******
kafka_sasl_mechanism: SCRAM-SHA-512
kafka_security_protocol: SASL_PLAINTEXT
- name: gke-stg-kafka
kafka_broker: gke-stg-kafka.gke-stg-kafka-brokers.kafka.svc:9095
kafka_username: kafka-plaintext-user
kafka_password: ****
kafka_sasl_mechanism: SCRAM-SHA-512
kafka_security_protocol: SASL_PLAINTEXT
```

Multi kafka cluster support

---

.github/workflows/build-binaries-and-brew.yaml

It didn't add all toolset directories to the binary by default - only manually configured directories
the robusta tool directory was added and broke the binary since it was missing the files,
Now will automatically add new tool directories

Fix brew build

---

holmes/plugins/toolsets/aks.yaml

This PR adds a list of read operations to Azure Kubernetes Service Services. Also, a cloud_provider tool is added to determined the cloud provider of the Kubernetes cluster in current context before we can have a toolset somewhere to host cloud provider related tools

chore(toolset): add Azure Kubernetes Service toolset

---

holmes/plugins/toolsets/aks.yaml

Normally, a user has to specify the cluster name, resource group and subscription ID to locate an AKS cluster. Considering it's not possible to extract these AKS info from the Kubernetes resources, To store the context on the cluster info, we require the user to set these environment RESOURCE_GROUP_NAME, CLUSTER_NAME and SUBSCRIPTION_ID to load aks toolset. This saves the effort to provide the same information every time they want to debug an AKS cluster.

DONGMERGE chore: allow customer to specify the AKS env in aks toolset

---

holmes/core/tools.py

Besides the normal yaml template parameter wrapped by bracket, a valid parameter can also be manipulated by filters appended with dot `.` or functions appended with vertical bar `|`.
test the following template will generate command like `Running command: kubectl exec -n test-ns dnsutils -- nslookup kubernetes.default.svc.cluster.local`
```
- name: "exec_on_dns_debug_pod"
description: "Run a command inside the DNS debugging pod"
command: "kubectl exec -n {{namespace|trim}} {{ pod_name }} -- {{ command.strip(\"'\") }}"
```
NOTE, `{{namespace|trim}}` has no practical use, and is for test only.

chore: infer filtered or function-guarded yaml tool parameter

---

.github/workflows/build-and-test.yaml
.github/workflows/llm-evaluation.yaml

Updating workflows to run only on code changes

---

server.py

For RCA streaming, `runbooks` were passed as `sections` which means the actual runbooks were not returned in the answer.

ROB-1457: issue with holmes not returning instructions

---

docs/installation.md
holmes/__init__.py
holmes/config.py
pyproject.toml

Fixes #466 
Note: this is only a partial fix, as now holmes will disable version checks altogether when installed from a github source version.
I think this is OK, as once we push to pypi users will be instructed to install from pypi and the version check will work for them.

Fix version warning from pipx

---

holmes/core/toolset_manager.py

We rely on check prerequisites to initialize the toolset configuration, but when the toolset is loaded from the cache, the prerequisites is not checked, and toolset configuration is not initialized.
Fix this by adding init_config method to initialize the toolset configuration when check prerequisites is not called.
fix: #532

fix(toolset): fix toolset config is not initialized when check prerequisites is not called

---

holmes/plugins/toolsets/aks-node-health.yaml
holmes/plugins/toolsets/aks.yaml

`az account list` does not return error when az cli does not log in to the Azure. Switch it to `az account show` to exit with error when azure login is done.

fix: use correct prerequisites to check az cli login status

---

holmes/config.py
holmes/plugins/prompts/_runbook_instructions.jinja2
tests/plugins/prompt/test_generic_ask_conversation.py

After the change, the _runbook_instructions.jinja2 is rendered as
```
issue on Kubernetes cluster\nlink: networking/dns_troubleshooting_instructions.md\n\nALWAYS try to find the runbooks that can provide troubleshooting    
instructions when the user describes an operational issue, debugging scenario, or asks for step‑by‑step troubleshooting.\nTo get the runbook details, use
`fetch_runbook` tool by comparing the runbook description with the user prompt.\nALWAYS follow the steps described in the runbook.\nIf you decided not to
follow one or more steps, ALWAYS explain why.
```

fix: runbook instruction should list all items clearly

---

holmes/plugins/prompts/__init__.py

holmes ask fails on windows machines with the error shown below 
`holmes ask  "why are my nginx pods are unhealthy?" --model=azure/gpt-4o ╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮ │ C:\Users\aritraghosh\pipx\venvs\holmesgpt\Lib\site-packages\holmes\main.py:341 in ask                               │ │                                                                                                                     │ │    338 │   │   slack_channel=slack_channel,                                                                         │ │    339 │   )                                                                                                        │ │    340 │ …

Adding fix to encode utf8

---

holmes/interactive.py

Previously, pressing 'G' in the /show modal would position the cursor at the end of the last line, causing UI confusion. This fix implements proper vim-like behavior where 'G' moves to the beginning of the last line by:
1. Moving to the end of all text
2. Using cursor_left with cursor_position_col to move back to line start

Fix 'G' key behavior in /show command to go to beginning of last line

---

holmes/main.py
holmes/utils/console/consts.py
holmes/utils/console/logging.py
holmes/utils/console/result.py

This PR moves the utils functions out of main.go to make utils function importal.

chore: move utils functions out of main.go

---

holmes/config.py
holmes/core/config.py
holmes/core/toolset_manager.py
holmes/interactive.py

export CONFIG_PATH_DIR=/home/azureuser/testholmes
running holmes aks gives the following files correctly
```
ls ~/testholmes 
config.yaml  history  toolsets_status.json
```

make config file dir configurable

---

docs/data-sources/builtin-toolsets/prometheus.md

Change from here https://github.com/robusta-dev/robusta/commit/38a5795fbc379c26f3bd6f6fd225b43ac0440b2e#diff-f7203e03e252047e645bcd4cf848cd5e71e401504b1ef3b66e51712cad3144f9L114

Copied mimir docs from robusta

---

holmes/core/tool_calling_llm.py

Fix tool call numbering to maintain sequential order across iterations

---

.github/workflows/build-and-test.yaml

Pull requests triggers duplicated builds for both push and pull_request. Limit the push event to master only to not trigger a redundant build.

don't trigger build on push non-master branch

---

pyproject.toml
tests/llm/fixtures/test_ask_holmes/151_disabled_toolsets_fallback_only/test_case.yaml
tests/llm/fixtures/test_ask_holmes/151_disabled_toolsets_fallback_only/toolsets.yaml
tests/llm/fixtures/test_ask_holmes/158_slack_chat_correct_date/test_case.yaml
tests/llm/fixtures/test_ask_holmes/159_prometheus_high_cardinality_cpu/test_case.yaml
tests/llm/fixtures/test_ask_holmes/30_basic_promql_graph_cluster_memory/test_case.yaml
tests/llm/fixtures/test_ask_holmes/31_basic_promql_graph_pod_memory/test_case.yaml
tests/llm/fixtures/test_ask_holmes/32_basic_promql_graph_pod_cpu/test_case.yaml
tests/llm/fixtures/test_ask_holmes/33_http_latency_graph/test_case.yaml
tests/llm/fixtures/test_ask_holmes/34_memory_graph/test_case.yaml
tests/llm/fixtures/test_ask_holmes/89_runbook_missing_cloudwatch/test_case.yaml
tests/llm/utils/mock_toolset.py
tests/llm/utils/property_manager.py
tests/llm/utils/test_case_utils.py

Add an eval to test for undesired behaviour reported by a customer: holmes refuses to investigate kafka lag using Prometheus, because it insists on telling the user to enable the Kafka toolset first.
This behaviour will be fixed in a separate PR - this PR only includes the eval.
This PR also improves error handling in the evals framework.

Small eval improvements + investigation-refusal eval

---

holmes/config.py
holmes/core/supabase_dal.py
holmes/plugins/toolsets/investigator/core_investigation.py

Make config.dal to optional since dal is passing down to tool_executor and to the tool. This protect the case when we don't use Dal is CLI.

mute unncessary info log for console

---

docs/stylesheets/extra.css

fix alignment issue in docs banner
